### ISSUE TITLE
LLama2 model invalid eos_token

### ISSUE THREAD

**Issue by siddhatiwari** [microsoft/toktrie#3]
It seems that toktrie doesn't properly tokenize the eos_token `</s>` for this model: https://huggingface.co/sophosympatheia/Midnight-Miqu-70B-v1.0/blob/main/tokenizer.json

Using the tokenizer.json provided by the model, `tokenize_special` tokenizes `</s>` into multiple token ids: [829, 29879, 29958].

I ran into this issue when running llgtrt (https://github.com/guidance-ai/llgtrt) and getting the following error for the model linked above:

```
INFO [llgtrt::tokenizer] Loading tokenizer from "/engine/tokenizer.json"
Error: tokenizer_config.json -> eos_token ("</s>") must tokenize to a single token
```

Running llgtrt with the llama3 tokenizer from the example works fine:
```
INFO [llgtrt::tokenizer] Loading tokenizer from "/engine/tokenizer.json"
INFO [llgtrt::chat] chat template result:
```

The error in llgtrt is on this line, where it checks that the eos_token tokenizes to a single token:

https://github.com/guidance-ai/llgtrt/blob/85d5a03449151c21d3fd0fa41e1b7a8d3f303ddf/llgtrt/src/tokenizer.rs#L72

I used this program to compare the outputs between toktrie and the hf tokenizers library:

https://gist.github.com/siddhatiwari/21149e29f4254623aa28ac7474239d75

Inputting `</s>` gives the results described above. Note that the hf tokenizer tokenizes `</s>` into a single token id: [2].
```
Enter text to tokenize (or 'quit' to exit): </s>

Toktrie Tokenizer:
Token IDs: [829, 29879, 29958]

HuggingFace Tokenizer:
Token IDs: [2]
```

**Comment by mmoskal** [comment]
The `tokenizer.json` for this model incorrectly (I think...) sets `"normalized": true`; if you change it to `false` (as it is in the base llama2 models) it works.

Generally, the problem is that I remove the "prepend space" filter from tokenizer, since I need it to work in the middle of a string.

I also did some fixes in llgtrt to handle the chat template in this model (and llama2).

**Comment by siddhatiwari** [comment]
Thanks, editing those fields in the tokenizer configs fixed the issue
